### ISSUE TITLE
Add semantic version tags

### ISSUE THREAD

**Issue by Remiii** [PUGX/PUGXGeoFormBundle#8]
Given a version number MAJOR.MINOR.PATCH (ie. http://semver.org/) could be a good things.

**Comment by garak** [comment]
I guess we need to reach some stability, then we could add a ``0.1.0`` tag?
Also, a branch-alias to next major release would be good

**Comment by Remiii** [comment]
@garak Ok this bundle is not fully tested but it's better to tag a version in order to fix a fist version and work with MAJOR, MINOR and PATCH... in order to follow backwards-compatibility and patch on each commit.

**Comment by Remiii** [comment]
@giorrrgio @garak Hey... do you have any news about "add semantic version tags"? I would like to add a PR with `Geocoder 3` but this version require `PHP 5.4` mini... so backwards-compatibility will be broken. :cry: In order to prevent that, add a first `v0.1.0` for this version would by a nice thing. But we can create simply a `new-version` branch in order to add this feature. What do you think? :mailbox_with_mail:

**Comment by garak** [comment]
Sorry for the late reply. I just tagged `v0.1.0`
